### ISSUE TITLE
Request - Add build options in the Makefile for cleveldb and rocksdb

### ISSUE THREAD

**Issue by effofxprime** [vidulum/mainnet#1]
For example, Osmosis and Stargaze both have added support for compiling their daemon with cleveldb and rocksdb support.
When you have time your leige, can we add these database options as a build option when compiling from source? :D 

https://github.com/public-awesome/stargaze/blob/main/Makefile

https://github.com/osmosis-labs/osmosis/blob/main/Makefile

**Comment by Corey-Code** [comment]
Feel free to submit a Pr with the changes and I will review.

**Comment by Corey-Code** [comment]
No PR was contributed. Closing issue...
